# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: upper_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'upper_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13upper_service.proto\x12\x0cUpperService\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"Y\n\x0cImageRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0f\n\x07part_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x12\n\nimage_data\x18\x04 \x01(\x0c\"!\n\x13GetFirstSnIdRequest\x12\n\n\x02sn\x18\x01 \x01(\t\"\"\n\x11GetFirstSnIdReply\x12\r\n\x05sn_id\x18\x01 \x01(\x04\"5\n\x17UpdateSnIdRemarkRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06remark\x18\x02 \x01(\t\"\xbd\x01\n\x15InsertDataToDbRequest\x12\n\n\x02sn\x18\x01 \x01(\t\x12\x15\n\rfeedstock_num\x18\x02 \x01(\x03\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x0f\n\x07ng_type\x18\x04 \x01(\t\x12\x14\n\x0cunitx_result\x18\x05 \x01(\t\x12\x10\n\x08\x44\x65viceID\x18\x06 \x01(\t\x12\x0e\n\x06remark\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\t\x12\x15\n\ris_timeout_sn\x18\t \x01(\x08\",\n\x0b\x43ommonReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9b\x03\n\x0cUpperService\x12@\n\x05Hello\x12\x1a.UpperService.HelloRequest\x1a\x19.UpperService.CommonReply\"\x00\x12G\n\x0cImageHandler\x12\x1a.UpperService.ImageRequest\x1a\x19.UpperService.CommonReply\"\x00\x12T\n\x0cGetFirstSnId\x12!.UpperService.GetFirstSnIdRequest\x1a\x1f.UpperService.GetFirstSnIdReply\"\x00\x12V\n\x10UpdateSnIdRemark\x12%.UpperService.UpdateSnIdRemarkRequest\x1a\x19.UpperService.CommonReply\"\x00\x12R\n\x0eInsertDataToDb\x12#.UpperService.InsertDataToDbRequest\x1a\x19.UpperService.CommonReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upper_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=37
  _globals['_HELLOREQUEST']._serialized_end=65
  _globals['_HELLORESPONSE']._serialized_start=67
  _globals['_HELLORESPONSE']._serialized_end=99
  _globals['_IMAGEREQUEST']._serialized_start=101
  _globals['_IMAGEREQUEST']._serialized_end=190
  _globals['_GETFIRSTSNIDREQUEST']._serialized_start=192
  _globals['_GETFIRSTSNIDREQUEST']._serialized_end=225
  _globals['_GETFIRSTSNIDREPLY']._serialized_start=227
  _globals['_GETFIRSTSNIDREPLY']._serialized_end=261
  _globals['_UPDATESNIDREMARKREQUEST']._serialized_start=263
  _globals['_UPDATESNIDREMARKREQUEST']._serialized_end=316
  _globals['_INSERTDATATODBREQUEST']._serialized_start=319
  _globals['_INSERTDATATODBREQUEST']._serialized_end=508
  _globals['_COMMONREPLY']._serialized_start=510
  _globals['_COMMONREPLY']._serialized_end=554
  _globals['_UPPERSERVICE']._serialized_start=557
  _globals['_UPPERSERVICE']._serialized_end=968
# @@protoc_insertion_point(module_scope)
