# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from backend.communication.grpc.proto import upper_service_pb2 as proto_dot_upper__service__pb2


class UpperServiceStub(object):
    """上位机服务定义  
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/UpperService.UpperService/Hello',
                request_serializer=proto_dot_upper__service__pb2.HelloRequest.SerializeToString,
                response_deserializer=proto_dot_upper__service__pb2.CommonReply.FromString,
                )
        self.ImageHandler = channel.unary_unary(
                '/UpperService.UpperService/ImageHandler',
                request_serializer=proto_dot_upper__service__pb2.ImageRequest.SerializeToString,
                response_deserializer=proto_dot_upper__service__pb2.CommonReply.FromString,
                )
        self.GetFirstSnId = channel.unary_unary(
                '/UpperService.UpperService/GetFirstSnId',
                request_serializer=proto_dot_upper__service__pb2.GetFirstSnIdRequest.SerializeToString,
                response_deserializer=proto_dot_upper__service__pb2.GetFirstSnIdReply.FromString,
                )
        self.UpdateSnIdRemark = channel.unary_unary(
                '/UpperService.UpperService/UpdateSnIdRemark',
                request_serializer=proto_dot_upper__service__pb2.UpdateSnIdRemarkRequest.SerializeToString,
                response_deserializer=proto_dot_upper__service__pb2.CommonReply.FromString,
                )
        self.InsertDataToDb = channel.unary_unary(
                '/UpperService.UpperService/InsertDataToDb',
                request_serializer=proto_dot_upper__service__pb2.InsertDataToDbRequest.SerializeToString,
                response_deserializer=proto_dot_upper__service__pb2.CommonReply.FromString,
                )


class UpperServiceServicer(object):
    """上位机服务定义  
    """

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImageHandler(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFirstSnId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSnIdRemark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertDataToDb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=proto_dot_upper__service__pb2.HelloRequest.FromString,
                    response_serializer=proto_dot_upper__service__pb2.CommonReply.SerializeToString,
            ),
            'ImageHandler': grpc.unary_unary_rpc_method_handler(
                    servicer.ImageHandler,
                    request_deserializer=proto_dot_upper__service__pb2.ImageRequest.FromString,
                    response_serializer=proto_dot_upper__service__pb2.CommonReply.SerializeToString,
            ),
            'GetFirstSnId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFirstSnId,
                    request_deserializer=proto_dot_upper__service__pb2.GetFirstSnIdRequest.FromString,
                    response_serializer=proto_dot_upper__service__pb2.GetFirstSnIdReply.SerializeToString,
            ),
            'UpdateSnIdRemark': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSnIdRemark,
                    request_deserializer=proto_dot_upper__service__pb2.UpdateSnIdRemarkRequest.FromString,
                    response_serializer=proto_dot_upper__service__pb2.CommonReply.SerializeToString,
            ),
            'InsertDataToDb': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertDataToDb,
                    request_deserializer=proto_dot_upper__service__pb2.InsertDataToDbRequest.FromString,
                    response_serializer=proto_dot_upper__service__pb2.CommonReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UpperService.UpperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UpperService(object):
    """上位机服务定义  
    """

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UpperService.UpperService/Hello',
            proto_dot_upper__service__pb2.HelloRequest.SerializeToString,
            proto_dot_upper__service__pb2.CommonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImageHandler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UpperService.UpperService/ImageHandler',
            proto_dot_upper__service__pb2.ImageRequest.SerializeToString,
            proto_dot_upper__service__pb2.CommonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFirstSnId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UpperService.UpperService/GetFirstSnId',
            proto_dot_upper__service__pb2.GetFirstSnIdRequest.SerializeToString,
            proto_dot_upper__service__pb2.GetFirstSnIdReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSnIdRemark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UpperService.UpperService/UpdateSnIdRemark',
            proto_dot_upper__service__pb2.UpdateSnIdRemarkRequest.SerializeToString,
            proto_dot_upper__service__pb2.CommonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertDataToDb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UpperService.UpperService/InsertDataToDb',
            proto_dot_upper__service__pb2.InsertDataToDbRequest.SerializeToString,
            proto_dot_upper__service__pb2.CommonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)