# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/upper_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/upper_service.proto',
  package='UpperService',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19proto/upper_service.proto\x12\x0cUpperService\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"Y\n\x0cImageRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0f\n\x07part_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x12\n\nimage_data\x18\x04 \x01(\x0c\"!\n\x13GetFirstSnIdRequest\x12\n\n\x02sn\x18\x01 \x01(\t\"\"\n\x11GetFirstSnIdReply\x12\r\n\x05sn_id\x18\x01 \x01(\x04\"5\n\x17UpdateSnIdRemarkRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06remark\x18\x02 \x01(\t\"\xbd\x01\n\x15InsertDataToDbRequest\x12\n\n\x02sn\x18\x01 \x01(\t\x12\x15\n\rfeedstock_num\x18\x02 \x01(\x03\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x0f\n\x07ng_type\x18\x04 \x01(\t\x12\x14\n\x0cunitx_result\x18\x05 \x01(\t\x12\x10\n\x08\x44\x65viceID\x18\x06 \x01(\t\x12\x0e\n\x06remark\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\t\x12\x15\n\ris_timeout_sn\x18\t \x01(\x08\",\n\x0b\x43ommonReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9b\x03\n\x0cUpperService\x12@\n\x05Hello\x12\x1a.UpperService.HelloRequest\x1a\x19.UpperService.CommonReply\"\x00\x12G\n\x0cImageHandler\x12\x1a.UpperService.ImageRequest\x1a\x19.UpperService.CommonReply\"\x00\x12T\n\x0cGetFirstSnId\x12!.UpperService.GetFirstSnIdRequest\x1a\x1f.UpperService.GetFirstSnIdReply\"\x00\x12V\n\x10UpdateSnIdRemark\x12%.UpperService.UpdateSnIdRemarkRequest\x1a\x19.UpperService.CommonReply\"\x00\x12R\n\x0eInsertDataToDb\x12#.UpperService.InsertDataToDbRequest\x1a\x19.UpperService.CommonReply\"\x00\x62\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='UpperService.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='UpperService.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=71,
)


_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='UpperService.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='UpperService.HelloResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=105,
)


_IMAGEREQUEST = _descriptor.Descriptor(
  name='ImageRequest',
  full_name='UpperService.ImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='UpperService.ImageRequest.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='part_id', full_name='UpperService.ImageRequest.part_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='UpperService.ImageRequest.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='UpperService.ImageRequest.image_data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=196,
)


_GETFIRSTSNIDREQUEST = _descriptor.Descriptor(
  name='GetFirstSnIdRequest',
  full_name='UpperService.GetFirstSnIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sn', full_name='UpperService.GetFirstSnIdRequest.sn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=231,
)


_GETFIRSTSNIDREPLY = _descriptor.Descriptor(
  name='GetFirstSnIdReply',
  full_name='UpperService.GetFirstSnIdReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sn_id', full_name='UpperService.GetFirstSnIdReply.sn_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=267,
)


_UPDATESNIDREMARKREQUEST = _descriptor.Descriptor(
  name='UpdateSnIdRemarkRequest',
  full_name='UpperService.UpdateSnIdRemarkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UpperService.UpdateSnIdRemarkRequest.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remark', full_name='UpperService.UpdateSnIdRemarkRequest.remark', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=322,
)


_INSERTDATATODBREQUEST = _descriptor.Descriptor(
  name='InsertDataToDbRequest',
  full_name='UpperService.InsertDataToDbRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sn', full_name='UpperService.InsertDataToDbRequest.sn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feedstock_num', full_name='UpperService.InsertDataToDbRequest.feedstock_num', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='UpperService.InsertDataToDbRequest.result', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ng_type', full_name='UpperService.InsertDataToDbRequest.ng_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unitx_result', full_name='UpperService.InsertDataToDbRequest.unitx_result', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DeviceID', full_name='UpperService.InsertDataToDbRequest.DeviceID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remark', full_name='UpperService.InsertDataToDbRequest.remark', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='UpperService.InsertDataToDbRequest.timestamp', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_timeout_sn', full_name='UpperService.InsertDataToDbRequest.is_timeout_sn', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=514,
)


_COMMONREPLY = _descriptor.Descriptor(
  name='CommonReply',
  full_name='UpperService.CommonReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='UpperService.CommonReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='UpperService.CommonReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=516,
  serialized_end=560,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE
DESCRIPTOR.message_types_by_name['ImageRequest'] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name['GetFirstSnIdRequest'] = _GETFIRSTSNIDREQUEST
DESCRIPTOR.message_types_by_name['GetFirstSnIdReply'] = _GETFIRSTSNIDREPLY
DESCRIPTOR.message_types_by_name['UpdateSnIdRemarkRequest'] = _UPDATESNIDREMARKREQUEST
DESCRIPTOR.message_types_by_name['InsertDataToDbRequest'] = _INSERTDATATODBREQUEST
DESCRIPTOR.message_types_by_name['CommonReply'] = _COMMONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'proto.upper_service_pb2'
  # @@protoc_insertion_point(class_scope:UpperService.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLORESPONSE,
  '__module__' : 'proto.upper_service_pb2'
  # @@protoc_insertion_point(class_scope:UpperService.HelloResponse)
  })
_sym_db.RegisterMessage(HelloResponse)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'proto.upper_service_pb2'
  # @@protoc_insertion_point(class_scope:UpperService.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

GetFirstSnIdRequest = _reflection.GeneratedProtocolMessageType('GetFirstSnIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFIRSTSNIDREQUEST,
  '__module__' : 'proto.upper_service_pb2'
  # @@protoc_insertion_point(class_scope:UpperService.GetFirstSnIdRequest)
  })
_sym_db.RegisterMessage(GetFirstSnIdRequest)

GetFirstSnIdReply = _reflection.GeneratedProtocolMessageType('GetFirstSnIdReply', (_message.Message,), {
  'DESCRIPTOR' : _GETFIRSTSNIDREPLY,
  '__module__' : 'proto.upper_service_pb2'
  # @@protoc_insertion_point(class_scope:UpperService.GetFirstSnIdReply)
  })
_sym_db.RegisterMessage(GetFirstSnIdReply)

UpdateSnIdRemarkRequest = _reflection.GeneratedProtocolMessageType('UpdateSnIdRemarkRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESNIDREMARKREQUEST,
  '__module__' : 'proto.upper_service_pb2'
  # @@protoc_insertion_point(class_scope:UpperService.UpdateSnIdRemarkRequest)
  })
_sym_db.RegisterMessage(UpdateSnIdRemarkRequest)

InsertDataToDbRequest = _reflection.GeneratedProtocolMessageType('InsertDataToDbRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTDATATODBREQUEST,
  '__module__' : 'proto.upper_service_pb2'
  # @@protoc_insertion_point(class_scope:UpperService.InsertDataToDbRequest)
  })
_sym_db.RegisterMessage(InsertDataToDbRequest)

CommonReply = _reflection.GeneratedProtocolMessageType('CommonReply', (_message.Message,), {
  'DESCRIPTOR' : _COMMONREPLY,
  '__module__' : 'proto.upper_service_pb2'
  # @@protoc_insertion_point(class_scope:UpperService.CommonReply)
  })
_sym_db.RegisterMessage(CommonReply)



_UPPERSERVICE = _descriptor.ServiceDescriptor(
  name='UpperService',
  full_name='UpperService.UpperService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=563,
  serialized_end=974,
  methods=[
  _descriptor.MethodDescriptor(
    name='Hello',
    full_name='UpperService.UpperService.Hello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_COMMONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ImageHandler',
    full_name='UpperService.UpperService.ImageHandler',
    index=1,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_COMMONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFirstSnId',
    full_name='UpperService.UpperService.GetFirstSnId',
    index=2,
    containing_service=None,
    input_type=_GETFIRSTSNIDREQUEST,
    output_type=_GETFIRSTSNIDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateSnIdRemark',
    full_name='UpperService.UpperService.UpdateSnIdRemark',
    index=3,
    containing_service=None,
    input_type=_UPDATESNIDREMARKREQUEST,
    output_type=_COMMONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InsertDataToDb',
    full_name='UpperService.UpperService.InsertDataToDb',
    index=4,
    containing_service=None,
    input_type=_INSERTDATATODBREQUEST,
    output_type=_COMMONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPPERSERVICE)

DESCRIPTOR.services_by_name['UpperService'] = _UPPERSERVICE

# @@protoc_insertion_point(module_scope)