/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/nav/controller': RouteRecordInfo<'/nav/controller', '/nav/controller', Record<never, never>, Record<never, never>>,
    '/nav/data': RouteRecordInfo<'/nav/data', '/nav/data', Record<never, never>, Record<never, never>>,
    '/nav/fixed_shoot': RouteRecordInfo<'/nav/fixed_shoot', '/nav/fixed_shoot', Record<never, never>, Record<never, never>>,
    '/nav/flying_shoot': RouteRecordInfo<'/nav/flying_shoot', '/nav/flying_shoot', Record<never, never>, Record<never, never>>,
    '/nav/info': RouteRecordInfo<'/nav/info', '/nav/info', Record<never, never>, Record<never, never>>,
    '/nav/log': RouteRecordInfo<'/nav/log', '/nav/log', Record<never, never>, Record<never, never>>,
    '/nav/run': RouteRecordInfo<'/nav/run', '/nav/run', Record<never, never>, Record<never, never>>,
    '/nav/workstation': RouteRecordInfo<'/nav/workstation', '/nav/workstation', Record<never, never>, Record<never, never>>,
  }
}
